import { describe, test, before, beforeEach, after } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import mysql from 'mysql2/promise';
import { makeCheckout } from '../src/services/checkout.js';
import { makeCancellation } from '../src/services/cancellation.js';
import { presentOrder } from '../src/services/order-presenter.js';
import { inTransaction } from '../src/utils/transaction.js';
import { installFixture, readCart, getDestination, deliveryDays, applyStockChange } from './mysql-fixture.mjs';

const url = process.env.M3_TEST_MYSQL_URL;
describe('M3 real MySQL 8.4 integration (isolated generated database)', { skip: !url, concurrency: false }, () => {
  let admin, pool, database;
  const actor={id:1,role:'customer'};
  const dependencies={readCart,getDestination,deliveryDays,applyStockChange};
  const checkout=makeCheckout(dependencies);
  const cancel=makeCancellation({applyStockChange});
  const body=(extra={})=>({fulfillment:'delivery',addressId:1,paymentMethod:'cod',cartVersion:3,requestKey:randomUUID(),...extra});
  before(async()=>{
    admin=await mysql.createConnection(url);
    const [[version]]=await admin.query('SELECT VERSION() AS version');
    assert.match(version.version,/^8\.4\./,'Use a disposable MySQL 8.4 server.');
    const candidate=`m3_checkout_test_${randomUUID().replaceAll('-','')}`;
    // Name is generated by this test; no existing database is selected or reset.
    await admin.query(`CREATE DATABASE \`${candidate}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci`);
    database=candidate;
    const parsed=new URL(url);
    pool=mysql.createPool({host:parsed.hostname,port:Number(parsed.port||3306),
      user:decodeURIComponent(parsed.username),password:decodeURIComponent(parsed.password),
      database,timezone:'Z',decimalNumbers:false,connectionLimit:6});
    const connection=await pool.getConnection();
    try { await connection.query("SET time_zone='+00:00'"); await installFixture(connection); }
    finally { connection.release(); }
  });
  after(async()=>{
    try { await pool?.end(); }
    finally {
      try { if(database && admin) await admin.query(`DROP DATABASE \`${database}\``); }
      finally { await admin?.end(); }
    }
  });
  beforeEach(async()=>{
    for(const table of ['order_item_categories','order_cancellations','order_operations',
      'order_status_history','payments','deliveries','checkout_requests','inventory_movements',
      'order_items','orders','cart_items']) await pool.query(`DELETE FROM ${table}`);
    await pool.query('UPDATE carts SET version=3');
    await pool.query('UPDATE variants SET stock=5,is_active=1');
    await pool.query("UPDATE variants SET price=IF(id=1,'40.00','15.00')");
    await pool.query('UPDATE products SET is_active=1,is_legacy=0');
    await pool.query('UPDATE cities SET is_active=1');
    await pool.query("INSERT INTO addresses(id,customer_id,recipient,line1,city,postal_code,country,city_id) VALUES(1,1,'A','Address A','Main','75001','US',1) ON DUPLICATE KEY UPDATE line1='Address A'");
    await pool.query('INSERT INTO cart_items VALUES(1,1,2),(1,2,1)');
  });
  async function balances(){
    const [rows]=await pool.query('SELECT id,stock FROM variants ORDER BY id'); return rows.map(r=>r.stock);
  }
  async function count(table){ const [[row]]=await pool.query(`SELECT COUNT(*) AS n FROM ${table}`); return row.n; }
  async function read(id){return inTransaction(pool,c=>presentOrder(c,id));}
  const code=(value)=>(error)=>error.code===value;
  test('COD checkout, complete row set, exact total and replay',async()=>{
    const input=body();const first=await checkout(pool,actor,input);
    assert.equal(first.status,201);assert.equal(first.data.total,'95.00');
    assert.equal(first.data.payment.status,'pending');assert.equal(first.data.status,'confirmed');
    assert.deepEqual(await balances(),[3,4]);
    const replay=await checkout(pool,actor,input);
    assert.equal(replay.status,200);assert.equal(replay.data.id,first.data.id);
    assert.equal(await count('orders'),1);assert.equal(await count('inventory_movements'),2);
    assert.equal(await count('cart_items'),0);
    const [[cart]]=await pool.query('SELECT version FROM carts WHERE id=1');assert.equal(cart.version,4);
  });
  test('decline persists exactly one audit and preserves cart/stock',async()=>{
    const input=body({paymentMethod:'card',simulationToken:'demo-declined'});
    await assert.rejects(checkout(pool,actor,input),code('PAYMENT_DECLINED'));
    await assert.rejects(checkout(pool,actor,input),code('PAYMENT_DECLINED'));
    assert.equal(await count('checkout_requests'),1);assert.equal(await count('orders'),0);
    assert.equal(await count('payments'),0);assert.equal(await count('cart_items'),2);
    assert.deepEqual(await balances(),[5,5]);
    await assert.rejects(checkout(pool,actor,{...input,simulationToken:'demo-approved'}),code('IDEMPOTENCY_CONFLICT'));
  });
  test('backorder allocates nothing; card cancellation refunds without restock',async()=>{
    await pool.query('UPDATE variants SET stock=0 WHERE id=2');
    const order=(await checkout(pool,actor,body({paymentMethod:'card',simulationToken:'demo-approved'}))).data;
    assert.equal(order.status,'backordered');assert.equal(order.payment.status,'paid');
    assert.equal(await count('inventory_movements'),0);assert.deepEqual(await balances(),[5,0]);
    const action={requestKey:randomUUID(),reason:'Changed plans'};
    const cancelled=await cancel(pool,actor,order.id,action);
    assert.equal(cancelled.payment.status,'refunded');assert.equal(cancelled.stockState,'none');
    await cancel(pool,actor,order.id,action);assert.deepEqual(await balances(),[5,0]);
    assert.equal(await count('order_cancellations'),1);
  });
  test('allocated cancellation restores once and voids COD',async()=>{
    const input=body();const order=(await checkout(pool,actor,input)).data;
    const action={requestKey:randomUUID(),reason:'Changed plans'};
    const cancelled=await cancel(pool,actor,order.id,action);
    assert.equal(cancelled.payment.status,'void');assert.equal(cancelled.stockState,'released');
    await cancel(pool,actor,order.id,action);assert.deepEqual(await balances(),[5,5]);
    assert.equal(await count('inventory_movements'),4);
    assert.equal((await checkout(pool,actor,input)).data.status,'cancelled');
    await assert.rejects(cancel(pool,actor,order.id,{...action,reason:'Different'}),code('IDEMPOTENCY_CONFLICT'));
  });
  test('failure after real trigger movement rolls back every effect',async()=>{
    const failing=makeCheckout({...dependencies,applyStockChange:async(c,change)=>{
      await applyStockChange(c,change);throw new Error('Forced after stock');
    }});
    await assert.rejects(failing(pool,actor,body()),/Forced after stock/);
    for(const table of ['orders','order_items','order_item_categories','payments','deliveries',
      'order_status_history','checkout_requests','inventory_movements']) assert.equal(await count(table),0,table);
    assert.equal(await count('cart_items'),2);assert.deepEqual(await balances(),[5,5]);
  });
  test('failure after cart clear restores cart version and every row',async()=>{
    const faultyPool={async getConnection(){
      const real=await pool.getConnection();
      return new Proxy(real,{get(target,key){
        if(key==='execute') return async(sql,params)=>{
          const result=await target.execute(sql,params);
          if(sql.startsWith('DELETE ci')) throw new Error('Forced after cart clear');
          return result;
        };
        const value=target[key];return typeof value==='function'?value.bind(target):value;
      }});
    }};
    await assert.rejects(checkout(faultyPool,actor,body()),/Forced after cart clear/);
    assert.equal(await count('orders'),0);assert.equal(await count('cart_items'),2);
    const [[cart]]=await pool.query('SELECT version FROM carts WHERE id=1');assert.equal(cart.version,3);
    assert.deepEqual(await balances(),[5,5]);
  });
  test('all four estimates use stored UTC date',async()=>{
    for(const main of [true,false])for(const shortage of [false,true]){
      await pool.query('DELETE FROM cart_items');await pool.query('UPDATE carts SET version=3 WHERE id=1');
      await pool.query('UPDATE variants SET stock=? WHERE id=1',[shortage?0:5]);
      await pool.query('INSERT INTO cart_items VALUES(1,1,1)');
      const order=(await checkout(pool,actor,body({addressId:main?1:3}))).data;
      const date=new Date(`${order.createdAt.slice(0,10)}T00:00:00Z`);
      date.setUTCDate(date.getUTCDate()+(main?5:7)+(shortage?3:0));
      assert.equal(order.delivery.estimatedDate,date.toISOString().slice(0,10));
    }
  });
  test('pickup card and address deletion preserve valid snapshots',async()=>{
    const {addressId,...input}=body({paymentMethod:'card',simulationToken:'demo-approved'});
    const pickup=(await checkout(pool,actor,{...input,fulfillment:'pickup',storeId:1})).data;
    assert.equal(pickup.addressSnapshot,null);assert.equal(pickup.delivery.destinationSnapshot.storeId,1);
    await pool.query('INSERT INTO cart_items VALUES(1,1,1)');
    const delivery=(await checkout(pool,actor,body({cartVersion:4}))).data;
    await pool.query('DELETE FROM addresses WHERE id=1');
    const [[row]]=await pool.query('SELECT address_id FROM deliveries WHERE order_id=?',[delivery.id]);
    assert.equal(row.address_id,null);assert.equal((await read(delivery.id)).delivery.destinationSnapshot.line1,'Address A');
    await assert.rejects(pool.query('UPDATE deliveries SET address_id=2 WHERE order_id=?',[pickup.id]));
  });
  test('ownership, wrong role, stale version and unknown fields',async()=>{
    await assert.rejects(checkout(pool,actor,body({addressId:2})),code('NOT_FOUND'));
    await assert.rejects(checkout(pool,{id:3,role:'admin'},body()),code('FORBIDDEN'));
    await assert.rejects(checkout(pool,actor,body({cartVersion:2})),code('CART_CHANGED'));
    await assert.rejects(checkout(pool,actor,body({total:'0.01'})),code('VALIDATION_ERROR'));
    const order=(await checkout(pool,actor,body())).data;
    await assert.rejects(cancel(pool,{id:2,role:'customer'},order.id,{requestKey:randomUUID(),reason:'X'}),code('NOT_FOUND'));
  });
  test('incomplete project data is rejected instead of labelled legacy',async()=>{
    const order=(await checkout(pool,actor,body())).data;
    await pool.query('DELETE FROM checkout_requests WHERE order_id=?',[order.id]);
    await assert.rejects(read(order.id),code('ORDER_DATA_INCOMPLETE'));
    await assert.rejects(cancel(pool,actor,order.id,{requestKey:randomUUID(),reason:'X'}),code('ORDER_DATA_INCOMPLETE'));
    assert.deepEqual(await balances(),[3,4]);
  });
  test('same key concurrent requests create one order', {timeout:15000},async()=>{
    const input=body();const results=await Promise.all([checkout(pool,actor,input),checkout(pool,actor,input)]);
    assert.deepEqual(results.map(r=>r.status).sort(),[200,201]);assert.equal(results[0].data.id,results[1].data.id);
    assert.equal(await count('orders'),1);assert.equal(await count('inventory_movements'),2);
  });
  test('two customers share one final unit without negative stock', {timeout:15000},async()=>{
    await pool.query('DELETE FROM cart_items');await pool.query('INSERT INTO cart_items VALUES(1,1,1),(2,1,1)');
    await pool.query('UPDATE variants SET stock=1 WHERE id=1');
    async function retry(customer,input){
      for(let n=0;n<3;n++)try{return await checkout(pool,customer,input);}catch(error){
        if(error.code!=='TRANSACTION_RETRY'||n===2)throw error;
      }
    }
    const results=await Promise.all([retry(actor,body()),retry({id:2,role:'customer'},body({addressId:2}))]);
    assert.deepEqual(results.map(r=>r.data.status).sort(),['backordered','confirmed']);
    assert.equal((await balances())[0],0);assert.equal(await count('inventory_movements'),1);
  });
});
