CREATE TABLE IF NOT EXISTS product_images (
 product_id INT UNSIGNED PRIMARY KEY,
 mime_type VARCHAR(30) NOT NULL,
 image_data MEDIUMBLOB NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB;
